sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint
    - node_js: "5"
      arch: ppc64le
    - node_js: "6"
      arch: ppc64le
    - node_js: "7"
      arch: ppc64le
    - node_js: "8"
      arch: ppc64le
    - node_js: "9"
      arch: ppc64le
    - node_js: "10"
      arch: ppc64le

env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
